# Generated by Django 3.1.6 on 2021-02-06 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_text', models.TextField()),
                ('translated_text', models.TextField()),
                ('status', models.CharField(choices=[('not initiated', 'not initiated'), ('in translation', 'in translation'), ('pending QA', 'pending QA'), ('approved', 'approved'), ('rejected', 'rejected'), ('sent to client', 'sent to client')], default='not initiated', max_length=25)),
                ('is_complete', models.BooleanField(default=False)),
                ('assigned_to', models.CharField(choices=[('qa', 'qa'), ('translator', 'translator'), ('none', 'none')], default='none', max_length=15)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('qa_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.qualityassurance')),
                ('translator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.translator')),
            ],
        ),
    ]
